# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:

  application:
    name: demo

  data:
    redis:
      repositories:
        enabled: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456789
    database: 5

# 应用服务 WEB 访问端口
server:
  port: 8802

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  config: classpath:logback-spring.xml

outagedetection: true
# 慢SQL记录标准 2 秒
outagedetectioninterval: 2
